### ISSUE TITLE
Support Ubuntu 20.04

### ISSUE THREAD

**Issue by datendelphin** [kosmtik/kosmtik#313]
I just tried to run `sudo npm -g install kosmtik` on ubuntu 20.04 and it failed. I am not familiar with node or javascript to see what the problem is, but I guess there will be some work to get it on 20.04. It wtill seems to work on 18.04.

I can attach the console output if desired.

**Comment by xamanu** [comment]
Can you try to install it from the repo:

```
git clone https://github.com/kosmtik/kosmtik.git
cd kosmtik
sudo npm install -g
```
It seems to work for me.

**Comment by AndreaGreco** [comment]
> Can you try to install it from the repo:
> 
> ```
> git clone https://github.com/kosmtik/kosmtik.git
> cd kosmtik
> sudo npm install -g
> ```
> 
> It seems to work for me (on Debian Bullseye).

Yes, work from Repo.
Is always better update package

**Comment by datendelphin** [comment]
It still can't build mapnik: `WARN lifecycle mapnik@4.5.2~install: cannot run in wd mapnik@4.5.2 node-pre-gyp install --fallback-to-build (wd=/home/kosmtik/kosmtik/node_modules/mapnik)`

which probably is the reason for the following error:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/kosmtik/kosmtik/node_modules/mapnik/lib/binding/mapnik_settings.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/kosmtik/kosmtik/node_modules/mapnik/lib/mapnik.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by Ircama** [comment]
ref. https://github.com/kosmtik/kosmtik/issues/302#issuecomment-790158285
